# Generated by Django 5.2.17 on 2026-09-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(blank=True, max_length=220)),
                ('product_type', models.CharField(default='simple', max_length=20)),
                ('status', models.CharField(default='publish', max_length=20)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('price', models.CharField(blank=True, max_length=40)),
                ('price_max', models.CharField(blank=True, max_length=40)),
                ('stock', models.CharField(blank=True, max_length=20)),
                ('qty', models.CharField(blank=True, max_length=20)),
                ('variation_count', models.PositiveIntegerField(default=0)),
                ('categories', models.CharField(blank=True, max_length=800)),
                ('family', models.CharField(db_index=True, default='other', max_length=40)),
                ('family_label', models.CharField(blank=True, max_length=80)),
                ('site_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True, max_length=800)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('price_text', models.CharField(blank=True, max_length=80)),
                ('verdict', models.CharField(default='uncertain', max_length=20)),
                ('visual_score', models.FloatField(default=0)),
                ('title_score', models.FloatField(default=0)),
                ('reasons', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='tahlil.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_path', models.CharField(max_length=500)),
                ('role', models.CharField(default='featured', max_length=20)),
                ('dhash', models.CharField(blank=True, max_length=64)),
                ('hist', models.JSONField(blank=True, default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tahlil.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
