# Generated by Django 5.2.17 on 2026-09-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahlil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RivalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_host', models.CharField(db_index=True, max_length=120)),
                ('shop_name', models.CharField(blank=True, max_length=120)),
                ('rival_ref', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=600)),
                ('url', models.URLField(max_length=900)),
                ('price', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('stock', models.CharField(blank=True, max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=900)),
                ('image_path', models.CharField(blank=True, max_length=200)),
                ('verdict', models.CharField(choices=[('match', 'match'), ('uncertain', 'uncertain')], default='uncertain', max_length=20)),
                ('visual_score', models.FloatField(default=0)),
                ('title_score', models.FloatField(default=0)),
                ('reasons', models.TextField(blank=True)),
                ('query_used', models.CharField(blank=True, max_length=200)),
                ('found_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivals', to='tahlil.product')),
            ],
            options={
                'ordering': ['-visual_score'],
                'constraints': [models.UniqueConstraint(fields=('product', 'url'), name='uniq_rival_per_product')],
            },
        ),
    ]
